### ISSUE TITLE
Add nice errors for when user has not enabled their I2C bus

### ISSUE THREAD

**Issue by ZodiusInfuser** [pimoroni/trilobot-python#36]
I have just tried pip install trilobot but still getting errors:
steve@raspberrypi:~/Pimoroni/trilobot/examples $ python3 show_underlighting.py
Trilobot Example: Show Underlighting

Traceback (most recent call last):
  File "/home/steve/Pimoroni/trilobot/examples/show_underlighting.py", line 16, in <module>
    tbot = Trilobot()
  File "/usr/local/lib/python3.9/dist-packages/trilobot/__init__.py", line 134, in __init__
    self.sn3218 = sn3218.SN3218()
  File "/usr/local/lib/python3.9/dist-packages/sn3218/__init__.py", line 26, in __init__
    self.i2c = SMBus(i2c_bus)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <function Trilobot.__del__ at 0x7f81c8b8b0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/trilobot/__init__.py", line 155, in __del__
    self.sn3218.disable()
AttributeError: 'Trilobot' object has no attribute 'sn3218'

_Originally posted by @IgnatiusB in https://github.com/pimoroni/trilobot-python/issues/32#issuecomment-1427034880_

**Comment by hartogsmith** [comment]
second that this would be great to have for people (like me) who forget to enable I2C

**Comment by Gadgetoid** [comment]
This actually caught me out, not because I hadn't enabled the bus but because I was testing the library before assembly and didn't expect "AttributeError: 'Trilobot' object has no attribute 'sn3218'" to mean "you have neither enabled i2c or connected any sensors."

Should be easy enough to check for the relevant i2c device nodes. Also it finally dawned on me that the LEDs are SN3218-based and not WS281x... 😆

**Comment by Gadgetoid** [comment]
Merg'd in the recent megalochange!
